# Version of docker-compose
version: '3'
# 
services:  
  phoenix:    
    build: .               
    volumes:
      - .:/app
    ports:      
      - "4000:4000"
    depends_on:      
      - db
  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_USER=mitchel
      - POSTGRES_PASS=mitchel
      - POSTGRES_DBNAME=river_api_dev
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5434:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
# Define the volumes
volumes:
  postgis-data:
